name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: list on nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish EasyAbp.UniappManagement.Application.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.Application/EasyAbp.UniappManagement.Application.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          
      - name: publish EasyAbp.UniappManagement.Application.Contracts.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.Application.Contracts/EasyAbp.UniappManagement.Application.Contracts.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.UniappManagement.Domain.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.Domain/EasyAbp.UniappManagement.Domain.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.UniappManagement.Domain.Shared.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.Domain.Shared/EasyAbp.UniappManagement.Domain.Shared.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.UniappManagement.EntityFrameworkCore.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.EntityFrameworkCore/EasyAbp.UniappManagement.EntityFrameworkCore.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.UniappManagement.HttpApi.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.HttpApi/EasyAbp.UniappManagement.HttpApi.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.UniappManagement.HttpApi.Client.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.HttpApi.Client/EasyAbp.UniappManagement.HttpApi.Client.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.UniappManagement.MongoDB.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.MongoDB/EasyAbp.UniappManagement.MongoDB.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: publish EasyAbp.UniappManagement.Web.dll
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/EasyAbp.UniappManagement.Web/EasyAbp.UniappManagement.Web.csproj
          VERSION_FILE_PATH: common.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}